ALTER TABLE Interfaces
MODIFY priority BIGINT(11) NOT NULL DEFAULT 1;

ALTER TABLE Properties
MODIFY priority BIGINT(11) NOT NULL DEFAULT 1;

ALTER TABLE Modules
MODIFY priority BIGINT(11) NOT NULL DEFAULT 1;